# Generated by Django 5.2 on 2025-04-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
