# Generated by Django 5.2 on 2025-04-29 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_category_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinformation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='product.product'),
        ),
    ]
