# Generated by Django 5.2 on 2025-04-29 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbanner',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to='product.product'),
        ),
    ]
