# Generated by Django 5.2 on 2025-04-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pure_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
