# Generated by Django 5.2 on 2025-04-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_pure_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_top_3',
            field=models.BooleanField(default=False),
        ),
    ]
