# Generated by Django 5.2 on 2025-05-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_is_top_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_code',
            field=models.CharField(blank=True, default=True, max_length=20),
        ),
    ]
