# Generated by Django 5.2 on 2025-05-01 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_color_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricerange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricerange', to='product.pricerange'),
        ),
    ]
