# Generated by Django 5.2 on 2025-04-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPcheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SmallIntegerField()),
                ('token', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
