# Generated by Django 5.2 on 2025-04-28 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_verifyemailcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyemailcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifyemailcode', to=settings.AUTH_USER_MODEL),
        ),
    ]
