# Generated by Django 5.2 on 2025-04-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_verifyemailcode_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth2fa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.SmallIntegerField()),
                ('phone', models.CharField(max_length=11)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
