# Generated by Django 5.2 on 2025-04-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auth2fa_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth2fa',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
